<table style="width:100%; font-size:11pt; border-collapse:collapse">
    <tr>
        <td colspan="2"
            style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   text-align:center;
                   font-weight:bold;
                   padding:8px;">
            Universidad de Oriente
        </td>
    </tr>
    <tr>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
                            Métodos Numéricos
        </td>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
            Clase 15 - Método de la bisección
        </td>
    </tr>
    <tr>
 

</table>

In [1]:
import math
import numpy as np
import pandas as pd

## Método de la bisección

In [4]:
def Biseccion(f,a,b,tol,maxiter):
    iters = 0
    error = tol+1

    while error>tol and iters<=maxiter:
        x = (a+b)/2
        error = (b-a)/2
        if f(a)*f(x)>0:
            a = x
        else:
            b = x
        iters = iters+1

    return [x,iters,error]

## Función crea una tabla con los resultados de las iteraciones

In [5]:
def Bisecciontabla(f,a,b,tol,maxiter):
    iters = 0
    error = tol+1
    lista_a = list(); lista_b = list()
    lista_a.append(a); lista_b.append(b);
    lista_x = list(); lista_e = list()

    while error>tol and iters<=maxiter:
        x = (a+b)/2
        error = (b-a)/2
        lista_e.append(error); lista_x.append(x)
        if f(a)*f(x)>0:
            a = x
        else:
            b = x
        iters = iters+1
        lista_a.append(a); lista_b.append(b);
    lista_a.pop(); lista_b.pop()
    tabla = pd.DataFrame({'a': lista_a, 'b': lista_b, 'x': lista_x, 'Errores': lista_e})
    pd.set_option('display.precision', 10)
    return tabla

### Ejemplo

Aplicar el método de la bisección para la ecuación $\sqrt{x}-\cos (x)=0$ en el intervalo $[0,1]$ con una tolerancia de $10^{-3}$

In [8]:
#Definimos f

f = lambda x: math.sqrt(x)-math.cos(x)
a = 0
b = 1
tol = 1e-3
maxiter = 30

##Llamamos a la funcion
x,iters,error = Biseccion(f,a,b,tol,maxiter)

In [9]:
print("La solucion obtenida fue x=%s" %x)
print("La cantidad de iteraciones realizadas fueron %s" %iters)
print("El error que se obtuvo fue de %s" %error)

La solucion obtenida fue x=0.6416015625
La cantidad de iteraciones realizadas fueron 10
El error que se obtuvo fue de 0.0009765625

### Mostrar la tabla con todas las iteraciones

In [11]:
Bisecciontabla(f,a,b,tol,maxiter)

          a            b             x       Errores
0  0.000000  1.000000000  0.5000000000  0.5000000000
1  0.500000  1.000000000  0.7500000000  0.2500000000
2  0.500000  0.750000000  0.6250000000  0.1250000000
3  0.625000  0.750000000  0.6875000000  0.0625000000
4  0.625000  0.687500000  0.6562500000  0.0312500000
5  0.625000  0.656250000  0.6406250000  0.0156250000
6  0.640625  0.656250000  0.6484375000  0.0078125000
7  0.640625  0.648437500  0.6445312500  0.0039062500
8  0.640625  0.644531250  0.6425781250  0.0019531250
9  0.640625  0.642578125  0.6416015625  0.0009765625

## Ejemplo

Encontrar la solucion de la ecuacion $e^{-x}(3.2 \sin(x)-0.5 \cos(x))=0$ 
en el intervalo $[3,4]$ con una tolerancia de $10^{-4}$

In [14]:
## Introducir f

f = lambda x: math.exp(-x)*(3.2*math.sin(x)-0.5*math.cos(x))
a = 3
b = 4
tol = 1e-4
maxiter = 30

In [15]:
x,iters,error = Biseccion(f,a,b,tol,maxiter)

In [16]:
print("La solucion obtenida fue x=%s" %x)
print("La cantidad de iteraciones realizadas fueron %s" %iters)
print("El error que se obtuvo fue de %s" %error)

La solucion obtenida fue x=3.29656982421875
La cantidad de iteraciones realizadas fueron 14
El error que se obtuvo fue de 6.103515625e-05

In [17]:
Bisecciontabla(f,a,b,tol,maxiter)

               a             b             x       Errores
0   3.0000000000  4.0000000000  3.5000000000  0.5000000000
1   3.0000000000  3.5000000000  3.2500000000  0.2500000000
2   3.2500000000  3.5000000000  3.3750000000  0.1250000000
3   3.2500000000  3.3750000000  3.3125000000  0.0625000000
4   3.2500000000  3.3125000000  3.2812500000  0.0312500000
5   3.2812500000  3.3125000000  3.2968750000  0.0156250000
6   3.2812500000  3.2968750000  3.2890625000  0.0078125000
7   3.2890625000  3.2968750000  3.2929687500  0.0039062500
8   3.2929687500  3.2968750000  3.2949218750  0.0019531250
9   3.2949218750  3.2968750000  3.2958984375  0.0009765625
10  3.2958984375  3.2968750000  3.2963867188  0.0004882812
11  3.2963867188  3.2968750000  3.2966308594  0.0002441406
12  3.2963867188  3.2966308594  3.2965087891  0.0001220703
13  3.2965087891  3.2966308594  3.2965698242  0.0000610352

## Ejercicio

Resolver $x^3-x-1=0$ en el intervalo de $[-1,2]$ con una tolerancia de $10^{-4}$

In [34]:
f = lambda x:x**3-x-1
a = -1
b = 2
tol = 1e-4
maxiter = 30

In [35]:
x,iters,error = Biseccion(f,a,b,tol,maxiter)

In [36]:
print("La solucion obtenida fue x=%s" %x)
print("La cantidad de iteraciones realizadas fueron %s" %iters)
print("El error que se obtuvo fue de %s" %error)

La solucion obtenida fue x=1.324798583984375
La cantidad de iteraciones realizadas fueron 15
El error que se obtuvo fue de 9.1552734375e-05

In [37]:
Bisecciontabla(f,a,b,tol,maxiter)

               a             b             x       Errores
0  -1.0000000000  2.0000000000  0.5000000000  1.5000000000
1   0.5000000000  2.0000000000  1.2500000000  0.7500000000
2   1.2500000000  2.0000000000  1.6250000000  0.3750000000
3   1.2500000000  1.6250000000  1.4375000000  0.1875000000
4   1.2500000000  1.4375000000  1.3437500000  0.0937500000
5   1.2500000000  1.3437500000  1.2968750000  0.0468750000
6   1.2968750000  1.3437500000  1.3203125000  0.0234375000
7   1.3203125000  1.3437500000  1.3320312500  0.0117187500
8   1.3203125000  1.3320312500  1.3261718750  0.0058593750
9   1.3203125000  1.3261718750  1.3232421875  0.0029296875
10  1.3232421875  1.3261718750  1.3247070312  0.0014648438
11  1.3247070312  1.3261718750  1.3254394531  0.0007324219
12  1.3247070312  1.3254394531  1.3250732422  0.0003662109
13  1.3247070312  1.3250732422  1.3248901367  0.0001831055
14  1.3247070312  1.3248901367  1.3247985840  0.0000915527