<table style="width:100%; font-size:11pt; border-collapse:collapse">
    <tr>
        <td colspan="2"
            style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   text-align:center;
                   font-weight:bold;
                   padding:8px;">
            Universidad de Oriente
        </td>
    </tr>
    <tr>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
                            Métodos Numéricos
        </td>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
            Clase 27 - Método de Traub - Sistemas no lineales
        </td>
    </tr>
    <tr>
 

</table>

# Método de Traub para sistemas de ecuaciones no lineales

In [4]:
import math
import numpy as np
import pandas as pd

## Función que implementa el método de Traub

In [5]:
def TraubSis(F,JF,x0,tol,maxiter):
    iters = 0 #Contador de iteraciones a cero
    error = tol+1
    while error>tol and iters<=maxiter:
        z = np.linalg.solve(JF(x0),F(x0)) #Se resuelve el sistema lineal
        y = x0-z
        w = np.linalg.solve(JF(x0),F(y)) #Se resuelve el sistema lineal
        x = y-w
        error = np.linalg.norm(x-x0) #Se encuentra el error con la norma
        x0 = x
        iters = iters+1
    return [x,iters,error]

## Función que muestra la tabla del método de Traub

In [6]:
def TraubSisTabla(F,JF,x0,tol,maxiter):
    iters = 0 #Contador de iteraciones a cero
    error = tol+1
    lista_error = list()
    lista_x = list()
    while error>tol and iters<=maxiter:
        z = np.linalg.solve(JF(x0),F(x0)) #Se resuelve el sistema lineal
        y = x0-z
        w = np.linalg.solve(JF(x0),F(y)) #Se resuelve el sistema lineal
        x = y-w
        lista_x.append(x)
        error = np.linalg.norm(x-x0) #Se encuentra el error con la norma
        lista_error.append(error)
        x0 = x
        iters = iters+1
    Tabla = pd.DataFrame()
    Tabla["x"] = [w[0] for w in lista_x]
    Tabla["y"] = [w[1] for w in lista_x]
    Tabla["Errores"] = lista_error
    pd.set_option('display.precision', 16)
    return Tabla

### Ejemplo 1

Encontrar la solución al sistemas de ecuaciones
\begin{align*}
x^2-2x-y+1/2&=0 \\
x^2+4y^2-4&=0
\end{align*}

Con el método de Traub usando las estimaciones iniciales $x_0=1$ e $y_0=1$ y una tolerancia de $10^{-10}$

In [7]:
def F(w):
    x,y = w
    S = np.zeros(2)
    S[0] = x**2-2*x-y+1/2
    S[1] = x**2+4*y**2-4
    return S

#Matriz Jacobiana
def JF(w):
    x,y = w
    M = np.zeros([2,2])
    M[0,0] = 2*x-2; M[0,1] = -1
    M[1,0] = 2*x; M[1,1] = 8*y
    return M

x0 = np.array([1,1])
tol = 1e-10
maxiter = 30

x,iters,error = TraubSis(F,JF,x0,tol,maxiter)

In [8]:
print("La solución al sistemas de ecuaciones es %s" %x)
print("La cantidad de iteraciones realizadas fueron %s"%iters)
print("El error que se obtuvo fue de %s" %error)

La solución al sistemas de ecuaciones es [-0.22221456  0.99380842]
La cantidad de iteraciones realizadas fueron 10
El error que se obtuvo fue de 1.1443916996305594e-16

In [9]:
TraubSisTabla(F,JF,x0,tol,maxiter)

                      x                    y               Errores
0 -134.1250000000000000  29.7500000000000000  138.1496584324405887
1  -49.7467587198494812  11.7962368655396013   86.2671734335813625
2  -18.1185494049631615   5.0402951184424953   32.3417125915810360
3   -6.2923589846899830   2.4643967730330312   12.1034719044761818
4   -1.9410326350418066   1.4523216239205525    4.4674754737540052
5   -0.4969337491500840   1.0738803118622093    1.4928628265537844
6   -0.2276597698629637   0.9954829245128033    0.2804543211725098
7   -0.2222146254154072   0.9938084407749376    0.0056967968054980
8   -0.2222145550597218   0.9938084185998337    0.0000000737675925
9   -0.2222145550597218   0.9938084185998338    0.0000000000000001

## Ejemplo 2

Resolver el siguiente sistema no lineal
\begin{align*}
4x^2-20x+\frac{1}{4}y^2+8 &=0 \\
\dfrac{1}{2}xy^2+2x-5y+8&=0
\end{align*}
Con una tolerancia de $10^{-6}$ y una estimación inicial de $\mathbf{x}^{(0)}=(0,0)$

In [10]:
def F(w):
    x,y = w
    S = np.zeros(2)
    S[0] = 4*x**2-20*x+1/4*y**2+8
    S[1] = 1/2*x*y**2+2*x-5*y+8
    return S

#Matriz Jacobiana
def JF(w):
    x,y = w
    M = np.zeros([2,2])
    M[0,0] = 8*x-20; M[0,1] = 1/2*y
    M[1,0] = 1/2*y**2+2; M[1,1] = x*y-5
    return M

x0 = np.array([0,0])
tol = 1e-10
maxiter = 30

x,iters,error = TraubSis(F,JF,x0,tol,maxiter)
print("La solución al sistema de ecuaciones es %s" %x)
print("La cantidad de iteraciones realizadas fueron %s"%iters)
print("El error que se obtuvo fue de %s" %error)

La solución al sistema de ecuaciones es [0.5 2. ]
La cantidad de iteraciones realizadas fueron 4
El error que se obtuvo fue de 5.017867255651201e-14

In [11]:
TraubSisTabla(F,JF,x0,tol,maxiter)

                    x                   y             Errores
0  0.4707200000000000  1.9121920000000001  1.9692779294106764
1  0.4999829020283487  1.9999147957135885  0.0924748956362142
2  0.4999999999999906  1.9999999999999507  0.0000869028828564
3  0.5000000000000000  2.0000000000000000  0.0000000000000502