<table style="width:100%; font-size:11pt; border-collapse:collapse">
    <tr>
        <td colspan="2"
            style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   text-align:center;
                   font-weight:bold;
                   padding:8px;">
            Universidad de Oriente
        </td>
    </tr>
    <tr>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
                            Métodos Numéricos
        </td>
        <td style="border: 1px #44a305 solid;
                   background-color:#F4F9E6;
                   color:#6ba340;
                   width:50%;
                   text-align:center;
                   padding:6px;">
            Clase 28 - Método de Jarrat - Sistemas No Lineales 
        </td>
    </tr>
    <tr>
 

</table>

# Método de Jarrat para sistemas de ecuaciones no lineales

In [14]:
import math
import numpy as np
import pandas as pd

## Función que implementa el método de Jarrat

In [15]:
def JarratSis(F,JF,x0,tol,maxiter):
    iters = 0 #Contador de iteraciones a cero
    error = tol+1
    while error>tol and iters<=maxiter:
        z = np.linalg.solve(JF(x0),F(x0)) #Se resuelve el sistema lineal
        y = x0-2/3*z
        v = np.dot(3*JF(y)+JF(x0),z) #Se resuelve el sistema lineal
        w = np.linalg.solve(3*JF(y)-JF(x0), v)
        x = x0-1/2*w
        error = np.linalg.norm(x-x0) #Se encuentra el error con la norma
        x0 = x
        iters = iters+1
    return [x,iters,error]

## Función que muestra la tabla del método de Newton

In [16]:
def JarratSisTabla(F,JF,x0,tol,maxiter):
    iters = 0 #Contador de iteraciones a cero
    error = tol+1
    lista_error = list()
    lista_x = list()
    while error>tol and iters<=maxiter:
        z = np.linalg.solve(JF(x0),F(x0)) #Se resuelve el sistema lineal
        y = x0-2/3*z
        v = np.dot(3*JF(y)+JF(x0),z) #Se resuelve el sistema lineal
        w = np.linalg.solve(3*JF(y)-JF(x0), v)
        x = x0-1/2*w
        lista_x.append(x)
        error = np.linalg.norm(x-x0) #Se encuentra el error con la norma
        lista_error.append(error)
        x0 = x
        iters = iters+1
    Tabla = pd.DataFrame()
    Tabla["x"] = [w[0] for w in lista_x]
    Tabla["y"] = [w[1] for w in lista_x]
    Tabla["Errores"] = lista_error
    pd.set_option('display.precision', 16)
    return Tabla

### Ejemplo 1

Encontrar la solución al sistemas de ecuaciones
\begin{align*}
f(x,y)&=x^3-x^2y+12 \\
g(x,y)&=2x^2+3x-y-9
\end{align*}

Con el método de Jarrat usando las estimaciones iniciales $x_0=-2$ e $y_0=-3$ y una tolerancia de $10^{-10}$

In [17]:
def F(w):
    x,y = w
    S = np.zeros(2)
    S[0] = x**3-x**2*y+12
    S[1] = 2*x**2+3*x-y-9
    return S

#Matriz Jacobiana
def JF(w):
    x,y = w
    M = np.zeros([2,2])
    M[0,0] = 3*x**2-2*x*y;  M[0,1] = -x**2
    M[1,0] = 4*x+3; M[1,1] = -1
    return M

x0 = np.array([-3,-2])
tol = 1e-10
maxiter = 30

x,iters,error = JarratSis(F,JF,x0,tol,maxiter)

In [18]:
print("La solución al sistemas de ecuaciones es %s" %x)
print("La cantidad de iteraciones realizadas fueron %s"%iters)
print("El error que se obtuvo fue de %s" %error)

La solución al sistemas de ecuaciones es [-2.8435149  -1.35939075]
La cantidad de iteraciones realizadas fueron 3
El error que se obtuvo fue de 6.280369834735101e-16

In [19]:
JarratSisTabla(F,JF,x0,tol,maxiter)

                    x                   y             Errores
0 -2.8435188127787274 -1.3593580679781605  0.6594758881254523
1 -2.8435148969287600 -1.3593907526747293  0.0000329184336013
2 -2.8435148969287596 -1.3593907526747289  0.0000000000000006

## Ejemplo 2

Aproximar la solución del sistema no lineal
\begin{align*}
f(x,y)&=e^xe^y+x \cos (y) \\
g(x,y)&=x+y-1
\end{align*}
Con una tolerancia de $10^{-7}$ y una estimación inicial de $\mathbf{x}^{(0)}=(2,1)$

In [20]:
def F(w):
    x,y = w
    S = np.zeros(2)
    S[0] = math.exp(x)*math.exp(y)+x*math.cos(y)
    S[1] = x+y-1
    return S

#Matriz Jacobiana
def JF(w):
    x,y = w
    M = np.zeros([2,2])
    M[0,0] = math.exp(x)*math.exp(y)+math.cos(y);  
    M[0,1] = math.exp(x)*math.exp(y)-x*math.sin(y)
    M[1,0] = 1; 
    M[1,1] = 1
    return M

x0 = np.array([2,1])
tol = 1e-12
maxiter = 30

x,iters,error = JarratSis(F,JF,x0,tol,maxiter)

In [21]:
print("La solución al sistemas de ecuaciones es %s" %x)
print("La cantidad de iteraciones realizadas fueron %s"%iters)
print("El error que se obtuvo fue de %s" %error)

La solución al sistemas de ecuaciones es [ 3.47063096 -2.47063096]
La cantidad de iteraciones realizadas fueron 4
El error que se obtuvo fue de 1.2560739669470201e-15

In [22]:
JarratSisTabla(F,JF,x0,tol,maxiter)

                    x                   y             Errores
0  3.1133151020331118 -2.1133151020331131  3.3063879749603573
1  3.4703487263381567 -2.4703487263381567  0.5049217937154139
2  3.4706309600316296 -2.4706309600316296  0.0003991387170680
3  3.4706309600316305 -2.4706309600316305  0.0000000000000013

## Ejemplo 3

Resolver el sistema de ecuaciones no lineales
\begin{align*}
4x+y-\sin (x)&=0 \\
\cos(xy)-e^{-x}+6y+2&=0
\end{align*}
Con una tolerancia de $10^{-12}$ y una estimación inicial de $\mathbf{x}^{0}=(0,0)$.

In [23]:
def F(w):
    x,y = w
    S = np.zeros(2)
    S[0] = 4*x+y-math.sin(x)
    S[1] = math.cos(x*y)-math.exp(-x)+6*y+2
    return S

#Matriz Jacobiana
def JF(w):
    x,y = w
    M = np.zeros([2,2])
    M[0,0] = 4-math.cos(x);  M[0,1] = 1
    M[1,0] = -y*math.sin(x*y)+math.exp(-x); M[1,1] = -x*math.sin(x*y)+6
    return M

x0 = np.array([0,0])
tol = 1e-12
maxiter = 30

x,iters,error = JarratSis(F,JF,x0,tol,maxiter)

In [24]:
print("La solución al sistemas de ecuaciones es %s" %x)
print("La cantidad de iteraciones realizadas fueron %s"%iters)
print("El error que se obtuvo fue de %s" %error)

La solución al sistemas de ecuaciones es [ 0.11711466 -0.35161151]
La cantidad de iteraciones realizadas fueron 3
El error que se obtuvo fue de 0.0

In [25]:
JarratSisTabla(F,JF,x0,tol,maxiter)

                    x                   y             Errores
0  0.1171194629763113 -0.3516272057955303  0.3706192931613676
1  0.1171146580282628 -0.3516115115899353  0.0000164132755722
2  0.1171146580282628 -0.3516115115899353  0.0000000000000000